/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgreePrivacy: typeof import('./../src/components/agree-privacy/index.vue')['default']
    PageNav: typeof import('./../src/components/page-nav/page-nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZInput: typeof import('./../src/components/z-input/index.vue')['default']
    ZModel: typeof import('./../src/components/z-model/index.vue')['default']
    ZPopup: typeof import('./../src/components/z-popup/index.vue')['default']
  }
}
